image:
  file: .gitpod.Dockerfile

tasks:
  # - init: |

  - command: |
      mix archive.install --force hex phx_new
      mkdir data

vscode:
  extensions:
    - redhat.vscode-yaml
    - yy0931.vscode-sqlite3-editor
    - gruntfuggly.todo-tree
    - jakebecker.elixir-ls
