interval: "500ms"
version: "3"

tasks:
  dev:
    cmds:
      - watchexec --restart --verbose --clear --wrap-process=session --stop-signal SIGTERM --exts gleam --watch src/ -- "gleam run"

  docker-build:
    cmds:
      - docker build -f Dockerfile . -t latest

  docker-run:
    cmds:
      - docker  run -it -p 8080:8080 latest

